enum ActionKind {
    Walking,
    Idle,
    Jumping,
    standL,
    standR,
    walkL,
    WalkR,
    walkD,
    standD,
    walkU,
    standU
}
function create_walking_animation () {
    animation_walking_left = animation.createAnimation(ActionKind.walkL, 100)
    for (let index = 0; index < 6; index++) {
        animation_walking_left.addAnimationFrame(img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            ......ccfffffffffff.....
            ......edeeddeefffffff...
            ......edddddddddeee.....
            .....eedfdddfddddee.....
            .....eeddfdddfdddeee....
            .....eeddfdddfdddeee....
            .....eeeddddddddeeee....
            .........bcffff.........
            ........bbcfffff........
            ........bcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            ......bbbcccccfffff.....
            .........dee.dee........
            .........cff.cff........
            ........................
            ........................
            `)
        animation_walking_left.addAnimationFrame(img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            ......ccfffffffffff.....
            ......edeeddeefffffff...
            ......edddddddddeee.....
            .....eedfdddfddddee.....
            .....eeddfdddfdddeee....
            .....eeddfdddfdddeee....
            .....eeeddddddddeeee....
            .........bcffff.........
            ........bbcfffff........
            ........bcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            ......bbbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `)
    }
    animation_walking_left.addAnimationFrame(img`
        ........................
        ............bccfff......
        ..........bcccffffff....
        ........bcccfffff.......
        .......bccffffffff......
        ...bbbbccfffffffff......
        ......ccfffffffffff.....
        ......edeeddeefffffff...
        ......edddddddddeee.....
        .....eeddddddddddee.....
        .....eedfdddfddddeee....
        .....eeddfdddfdddeee....
        .....eeeddddddddeeee....
        .........bcffff.........
        ........bbcfffff........
        ........bcccffff........
        ........bcccfffff.......
        .......bbccccfffff......
        .......bbccccffffff.....
        ......bbbcccccfffff.....
        .........dee.dee........
        .........cff.cff........
        ........................
        ........................
        `)
    animation_walking_left.addAnimationFrame(img`
        ........................
        ............bccfff......
        ..........bcccffffff....
        ........bcccfffff.......
        .......bccffffffff......
        ...bbbbccfffffffff......
        ......ccfffffffffff.....
        ......edeeddeefffffff...
        ......edddddddddeee.....
        .....eedfdddfddddee.....
        .....eeddfdddfdddeee....
        .....eeddfdddfdddeee....
        .....eeeddddddddeeee....
        .........bcffff.........
        ........bbcfffff........
        ........bcccffff........
        ........bcccfffff.......
        .......bbccccfffff......
        .......bbccccffffff.....
        ......bbbcccccfffff.....
        ..........dedee.........
        ..........cfcff.........
        ........................
        ........................
        `)
    animation_walking_right = animation.createAnimation(ActionKind.WalkR, 100)
    animation_walking_right.addAnimationFrame(img`
        ........................
        ......fffccb............
        ....ffffffcccb..........
        .......fffffcccb........
        ......ffffffffccb.......
        ......fffffffffccbbbb...
        .....fffffffffffcc......
        ...fffffffeeddeede......
        .....eeeddddddddde......
        .....eeddddfdddfdee.....
        ....eeedddfdddfddee.....
        ....eeedddfdddfddee.....
        ....eeeeddddddddeee.....
        .........ffffcb.........
        ........fffffcbb........
        ........ffffcccb........
        .......fffffcccb........
        ......fffffccccbb.......
        .....ffffffccccbb.......
        .....fffffcccccbbb......
        ........eed.eed.........
        ........ffc.ffc.........
        ........................
        ........................
        `)
    animation_walking_right.addAnimationFrame(img`
        ........................
        ......fffccb............
        ....ffffffcccb..........
        .......fffffcccb........
        ......ffffffffccb.......
        ......fffffffffccbbbb...
        .....fffffffffffcc......
        ...fffffffeeddeede......
        .....eeeddddddddde......
        .....eeddddfdddfdee.....
        ....eeedddfdddfddee.....
        ....eeedddfdddfddee.....
        ....eeeeddddddddeee.....
        .........ffffcb.........
        ........fffffcbb........
        ........ffffcccb........
        .......fffffcccb........
        ......fffffccccbb.......
        .....ffffffccccbb.......
        .....fffffcccccbbb......
        .........eeded..........
        .........ffcfc..........
        ........................
        ........................
        `)
    animation_walking_right.addAnimationFrame(img`
        ........................
        ......fffccb............
        ....ffffffcccb..........
        .......fffffcccb........
        ......ffffffffccb.......
        ......fffffffffccbbbb...
        .....fffffffffffcc......
        ...fffffffeeddeede......
        .....eeeddddddddde......
        .....eeddddfdddfdee.....
        ....eeedddfdddfddee.....
        ....eeedddfdddfddee.....
        ....eeeeddddddddeee.....
        .........ffffcb.........
        ........fffffcbb........
        ........ffffcccb........
        .......fffffcccb........
        ......fffffccccbb.......
        .....ffffffccccbb.......
        .....fffffcccccbbb......
        ........eed.eed.........
        ........ffc.ffc.........
        ........................
        ........................
        `)
    animation_walking_down = animation.createAnimation(ActionKind.walkD, 100)
    for (let index = 0; index < 6; index++) {
        animation_walking_down.addAnimationFrame(img`
            ........................
            ..........ffcc..........
            .........ffcbfccc.......
            ........fffccbfc........
            ......ffffcccbb.........
            ......ffffcccccbb.......
            ......fffcccccccc.......
            ..fffffffccccccccbbbb...
            ....fffffcccccccbbb.....
            .....eeedddddddeee......
            ....eeedfdddfdddeee.....
            ....eeeddfdddfddeee.....
            ....eeeddfdddfddeee.....
            ....eeedddddddddeee.....
            ......e.fffccbb.e.......
            ........ffccccb.........
            .......fffccccb.........
            .......ffcccccbb........
            ......fffcccccbb........
            ......fffcccccbbb.......
            ........eed.eed.........
            ........ffc.ffc.........
            ........................
            ........................
            `)
        animation_walking_down.addAnimationFrame(img`
            ........................
            ..........ffcc..........
            .........ffcbfccc.......
            ........fffccbfc........
            ......ffffcccbb.........
            ......ffffcccccbb.......
            ......fffcccccccc.......
            ..fffffffccccccccbbbb...
            ....fffffcccccccbbb.....
            .....eeedddddddeee......
            ....eeedfdddfdddeee.....
            ....eeeddfdddfddeee.....
            ....eeeddfdddfddeee.....
            ....eeedddddddddeee.....
            ......e.fffccbb.e.......
            ........ffccccb.........
            .......fffccccb.........
            .......ffcccccbb........
            ......fffcccccbb........
            ......fffcccccbbb.......
            ........ffc.eed.........
            ............ffc.........
            ........................
            ........................
            `)
        animation_walking_down.addAnimationFrame(img`
            ........................
            ..........ffcc..........
            .........ffcbfccc.......
            ........fffccbfc........
            ......ffffcccbb.........
            ......ffffcccccbb.......
            ......fffcccccccc.......
            ..fffffffccccccccbbbb...
            ....fffffcccccccbbb.....
            .....eeedddddddeee......
            ....eeedfdddfdddeee.....
            ....eeeddfdddfddeee.....
            ....eeeddfdddfddeee.....
            ....eeedddddddddeee.....
            ......e.fffccbb.e.......
            ........ffccccb.........
            .......fffccccb.........
            .......ffcccccbb........
            ......fffcccccbb........
            ......fffcccccbbb.......
            ........eed.eed.........
            ........ffc.ffc.........
            ........................
            ........................
            `)
        animation_walking_down.addAnimationFrame(img`
            ........................
            ..........ffcc..........
            .........ffcbfccc.......
            ........fffccbfc........
            ......ffffcccbb.........
            ......ffffcccccbb.......
            ......fffcccccccc.......
            ..fffffffccccccccbbbb...
            ....fffffcccccccbbb.....
            .....eeedddddddeee......
            ....eeedfdddfdddeee.....
            ....eeeddfdddfddeee.....
            ....eeeddfdddfddeee.....
            ....eeedddddddddeee.....
            ......e.fffccbb.e.......
            ........ffccccb.........
            .......fffccccb.........
            .......ffcccccbb........
            ......fffcccccbb........
            ......fffcccccbbb.......
            ........eed.ffc.........
            ........ffc.............
            ........................
            ........................
            `)
    }
    animation_walking_down.addAnimationFrame(img`
        ........................
        ..........ffcc..........
        .........ffcbfccc.......
        ........fffccbfc........
        ......ffffcccbb.........
        ......ffffcccccbb.......
        ......fffcccccccc.......
        ..fffffffccccccccbbbb...
        ....fffffcccccccbbb.....
        .....eeedddddddeee......
        ....eeedfdddfdddeee.....
        ....eeeddfdddfddeee.....
        ....eeeddfdddfddeee.....
        ....eeedddddddddeee.....
        ......e.fffccbb.e.......
        ........ffccccb.........
        .......fffccccb.........
        .......ffcccccbb........
        ......fffcccccbb........
        ......fffcccccbbb.......
        ........eed.eed.........
        ........ffc.ffc.........
        ........................
        ........................
        `)
    animation_walking_down.addAnimationFrame(img`
        ........................
        ..........ffcc..........
        .........ffcbfccc.......
        ........fffccbfc........
        ......ffffcccbb.........
        ......ffffcccccbb.......
        ......fffcccccccc.......
        ..fffffffccccccccbbbb...
        ....fffffcccccccbbb.....
        .....eeedddddddeee......
        ....eeedddddddddeee.....
        ....eeedfdddfdddeee.....
        ....eeeddfdddfddeee.....
        ....eeedddddddddeee.....
        ......e.fffccbb.e.......
        ........ffccccb.........
        .......fffccccb.........
        .......ffcccccbb........
        ......fffcccccbb........
        ......fffcccccbbb.......
        ........eed.ffc.........
        ........ffc.............
        ........................
        ........................
        `)
    animation_walking_up = animation.createAnimation(ActionKind.walkU, 100)
    animation_walking_up.addAnimationFrame(img`
        ........................
        ..........fcb...........
        .........fffcb..........
        ........ffffcb..........
        ......fffffffbc.........
        ......fffffcfbcbb.......
        ......ffffccffbcb.......
        ......fffccccfbcb.......
        .ffffffffccccfbcbbbbb...
        ...fffffccccccccbb......
        ....effccccccccceee.....
        ....eeeccccccccdeee.....
        ....eeedddddddddeee.....
        ......eddddddddde.......
        ........fffccbb.........
        ........ffccccb.........
        .......fffccccb.........
        .......ffcccccbb........
        ......fffcccccbb........
        ......fffcccccbbb.......
        ........eed.eed.........
        ........ffc.ffc.........
        ........................
        ........................
        `)
    animation_walking_up.addAnimationFrame(img`
        ........................
        ..........fcb...........
        .........fffcb..........
        ........ffffcb..........
        ......fffffffbc.........
        ......fffffcfbcbb.......
        ......ffffccffbcb.......
        ......fffccccfbcb.......
        .ffffffffccccfbcbbbbb...
        ...fffffccccccccbb......
        ....effccccccccceee.....
        ....eeeccccccccdeee.....
        ....eeedddddddddeee.....
        ......eddddddddde.......
        ........fffccbb.........
        ........ffccccb.........
        .......fffccccb.........
        .......ffcccccbb........
        ......fffcccccbb........
        ......fffcccccbbb.......
        ........eed.ffc.........
        ........ffc.............
        ........................
        ........................
        `)
    animation_walking_up.addAnimationFrame(img`
        ........................
        ..........fcb...........
        .........fffcb..........
        ........ffffcb..........
        ......fffffffbc.........
        ......fffffcfbcbb.......
        ......ffffccffbcb.......
        ......fffccccfbcb.......
        .ffffffffccccfbcbbbbb...
        ...fffffccccccccbb......
        ....effccccccccceee.....
        ....eeeccccccccdeee.....
        ....eeedddddddddeee.....
        ......eddddddddde.......
        ........fffccbb.........
        ........ffccccb.........
        .......fffccccb.........
        .......ffcccccbb........
        ......fffcccccbb........
        ......fffcccccbbb.......
        ........eed.eed.........
        ........ffc.ffc.........
        ........................
        ........................
        `)
    animation_walking_up.addAnimationFrame(img`
        ........................
        ..........fcb...........
        .........fffcb..........
        ........ffffcb..........
        ......fffffffbc.........
        ......fffffcfbcbb.......
        ......ffffccffbcb.......
        ......fffccccfbcb.......
        .ffffffffccccfbcbbbbb...
        ...fffffccccccccbb......
        ....effccccccccceee.....
        ....eeeccccccccdeee.....
        ....eeedddddddddeee.....
        ......eddddddddde.......
        ........fffccbb.........
        ........ffccccb.........
        .......fffccccb.........
        .......ffcccccbb........
        ......fffcccccbb........
        ......fffcccccbbb.......
        ........ffc.eed.........
        ............ffc.........
        ........................
        ........................
        `)
    animation.attachAnimation(Freya, animation_walking_left)
    animation.attachAnimation(Freya, animation_walking_down)
    animation.attachAnimation(Freya, animation_walking_right)
    animation.attachAnimation(Freya, animation_walking_up)
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.setAction(Freya, ActionKind.walkU)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    let facingleft = 0
    if (facingleft == 0) {
        animation.runImageAnimation(
        Freya,
        [img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            ......ccfffffffffff.....
            ......edeeddeefffffff...
            ......edddddddddeee.....
            .....eedfdddfddddee.....
            .....eeddfdddfdddeee....
            .....eeddfdddfdddeee....
            .....eeeddddddddeeee....
            .........bcffff.........
            ........bbcfffff........
            ........bcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            ......bbbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            ......ccfffffffffff.....
            ......edeeddeefffffff...
            ......edddddddddeee.....
            .....eeddddddddddee.....
            .....eedfdddfddddeee....
            .....eeddfdddfdddeee....
            .....eeeddddddddeeee....
            .........bcffff.........
            ........bbcfffff........
            .......cbcccffff........
            .......cbcccfffff.......
            ......cbbccccfffff......
            ......cbbccccffffff.....
            ......bbbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            ......ccfffffffffff.....
            ......edeeddeefffffff...
            ......edddddddddeee.....
            .....eeddddddddddee.....
            .....eedfdddfddddeee....
            .....eeddfdddfdddeee....
            .....eeeddddddddeeee....
            .........bcffff.........
            ......ccbbcfffff........
            .....cccbcccffff........
            .....cdcbcccfffff.......
            .....cdbbccccfffff......
            .......bbccccffffff.....
            ......bbbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            ......ccfffffffffff.....
            ......edeeddeefffffff...
            ......edddddddddeee.....
            .....eedfdddfddddee.....
            .....eeddfdddfdddeee....
            .....eeddfdddfdddeee....
            .....eeeddddddddeeee....
            .........bcffff.........
            ......bbbbcfffff........
            ....bbbcbcccffff........
            ....bdccbcccfffff.......
            ....cdcbbccccfffff......
            ......ebbccccffffff.....
            ......bbbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            ......ccfffffffffff.....
            ......edeeddeefffffff...
            ......edddddddddeee.....
            .....eedfdddfddddee.....
            .....eeddfdddfdddeee....
            .....eeddfdddfdddeee....
            .....eeeddddddddeeee....
            .9.......bcffff.........
            .ee.bbbbbbcfffff........
            ..eedbbcbcccffff........
            ....dcccbcccfffff.......
            ..1..ccbbccccfffff......
            ..11...bbccccffffff.....
            ...111.bbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            9.....ccfffffffffff.....
            ..9...edeeddeefffffff...
            91....edddddddddeee.....
            99.9.eedfdddfddddee.....
            ..e..eeddfdddfdddeee....
            9..e.eeddfdddfdddeee....
            ...dbbeeddddddddeeee....
            ...bbbbbbbcffff.........
            ...ccccbbbcfffff........
            ....ccccbcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            .......bbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            9.....ccfffffffffff.....
            ..9...edeeddeefffffff...
            91....edddddddddeee.....
            99.9.eedfdddfddddee.....
            ..e..eeddfdddfdddeee....
            9..e.eeddfdddfdddeee....
            ...dbbeeddddddddeeee....
            ...bbbbbbbcffff.........
            ...ccccbbbcfffff........
            ....ccccbcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            .......bbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            .9.bbbbccfffffffff......
            ......ccfffffffffff.....
            ...9..edeeddeefffffff...
            91....edddddddddeee.....
            99..9eedfdddfddddee.....
            ..e..eeddfdddfdddeee....
            ...e.eeddfdddfdddeee....
            9..dbbeeddddddddeeee....
            ...bbbbbbbcffff.........
            ...ccccbbbcfffff........
            ....ccccbcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            .......bbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            .9.bbbbccfffffffff......
            ......ccfffffffffff.....
            ...9..edeeddeefffffff...
            91....edddddddddeee.....
            99..9eedfdddfddddee.....
            ..e..eeddfdddfdddeee....
            ...e.eeddfdddfdddeee....
            9..dbbeeddddddddeeee....
            ...bbbbbbbcffff.........
            ...ccccbbbcfffff........
            ....ccccbcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            .......bbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            9.....ccfffffffffff.....
            ..9...edeeddeefffffff...
            91....edddddddddeee.....
            99.9.eedfdddfddddee.....
            ..e..eeddfdddfdddeee....
            9..e.eeddfdddfdddeee....
            ...dbbeeddddddddeeee....
            ...bbbbbbbcffff.........
            ...ccccbbbcfffff........
            ....ccccbcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            .......bbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            9.....ccfffffffffff.....
            ..9...edeeddeefffffff...
            91....edddddddddeee.....
            99.9.eedfdddfddddee.....
            ..e..eeddfdddfdddeee....
            9..e.eeddfdddfdddeee....
            ...dbbeeddddddddeeee....
            ...bbbbbbbcffff.........
            ...ccccbbbcfffff........
            ....ccccbcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            .......bbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            .9.bbbbccfffffffff......
            ......ccfffffffffff.....
            ...9..edeeddeefffffff...
            91....edddddddddeee.....
            99..9eedfdddfddddee.....
            ..e..eeddfdddfdddeee....
            ...e.eeddfdddfdddeee....
            9..dbbeeddddddddeeee....
            ...bbbbbbbcffff.........
            ...ccccbbbcfffff........
            ....ccccbcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            .......bbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            .9.bbbbccfffffffff......
            ......ccfffffffffff.....
            ...9..edeeddeefffffff...
            91....edddddddddeee.....
            99..9eedfdddfddddee.....
            ..e..eeddfdddfdddeee....
            ...e.eeddfdddfdddeee....
            9..dbbeeddddddddeeee....
            ...bbbbbbbcffff.........
            ...ccccbbbcfffff........
            ....ccccbcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            .......bbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `,img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            ......ccfffffffffff.....
            ......edeeddeefffffff...
            ......edddddddddeee.....
            .....eedfdddfddddee.....
            .....eeddfdddfdddeee....
            .....eeddfdddfdddeee....
            .....eeeddddddddeeee....
            .........bcffff.........
            ........bbcfffff........
            ........bcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            ......bbbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `],
        100,
        false
        )
    }
    if (facingleft == 1) {
        animation.runImageAnimation(
        Freya,
        [img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb...
            .....fffffffffffcc......
            ...fffffffeeddeede......
            .....eeeddddddddde......
            .....eeddddfdddfdee.....
            ....eeedddfdddfddee.....
            ....eeedddfdddfddee.....
            ....eeeeddddddddeee.....
            .........ffffcb.........
            ........fffffcbb........
            ........ffffcccb........
            .......fffffcccb........
            ......fffffccccbb.......
            .....ffffffccccbb.......
            .....fffffcccccbbb......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb...
            .....fffffffffffcc......
            ...fffffffeeddeede......
            .....eeeddddddddde......
            .....eeddddddddddee.....
            ....eeeddddfdddfdee.....
            ....eeedddfdddfddee.....
            ....eeeeddddddddeee.....
            .........ffffcb.........
            ........fffffcbb........
            ........ffffcccbc.......
            .......fffffcccbc.......
            ......fffffccccbbc......
            .....ffffffccccbbc......
            .....fffffcccccbbb......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb...
            .....fffffffffffcc......
            ...fffffffeeddeede......
            .....eeeddddddddde......
            .....eeddddddddddee.....
            ....eeeddddfdddfdee.....
            ....eeedddfdddfddee.....
            ....eeeeddddddddeee.....
            .........ffffcb.........
            ........fffffcbbcc......
            ........ffffcccbccc.....
            .......fffffcccbcdc.....
            ......fffffccccbbdc.....
            .....ffffffccccbb.......
            .....fffffcccccbbb......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb...
            .....fffffffffffcc......
            ...fffffffeeddeede......
            .....eeeddddddddde......
            .....eeddddfdddfdee.....
            ....eeedddfdddfddee.....
            ....eeedddfdddfddee.....
            ....eeeeddddddddeee.....
            .........ffffcb.........
            ........fffffcbbbb......
            ........ffffcccbcbbb....
            .......fffffcccbccdb....
            ......fffffccccbbcdc....
            .....ffffffccccbbe......
            .....fffffcccccbbb......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb...
            .....fffffffffffcc......
            ...fffffffeeddeede......
            .....eeeddddddddde......
            .....eeddddfdddfdee.....
            ....eeedddfdddfddee.....
            ....eeedddfdddfddee.....
            ....eeeeddddddddeee.....
            .........ffffcb.......9.
            ........fffffcbbbbbb.ee.
            ........ffffcccbcbbdee..
            .......fffffcccbcccd....
            ......fffffccccbbcc..1..
            .....ffffffccccbb...11..
            .....fffffcccccbb.111...
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb...
            .....fffffffffffcc.....9
            ...fffffffeeddeede...9..
            .....eeeddddddddde....19
            .....eeddddfdddfdee.9.99
            ....eeedddfdddfddee..e..
            ....eeedddfdddfddee.e..9
            ....eeeeddddddddeebbd...
            .........ffffcbbbbbbb...
            ........fffffcbbbcccc...
            ........ffffcccbcccc....
            .......fffffcccb........
            ......fffffccccbb.......
            .....ffffffccccbb.......
            .....fffffcccccbb.......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb...
            .....fffffffffffcc.....9
            ...fffffffeeddeede...9..
            .....eeeddddddddde....19
            .....eeddddfdddfdee.9.99
            ....eeedddfdddfddee..e..
            ....eeedddfdddfddee.e..9
            ....eeeeddddddddeebbd...
            .........ffffcbbbbbbb...
            ........fffffcbbbcccc...
            ........ffffcccbcccc....
            .......fffffcccb........
            ......fffffccccbb.......
            .....ffffffccccbb.......
            .....fffffcccccbb.......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb.9.
            .....fffffffffffcc......
            ...fffffffeeddeede..9...
            .....eeeddddddddde....19
            .....eeddddfdddfdee9..99
            ....eeedddfdddfddee..e..
            ....eeedddfdddfddee.e...
            ....eeeeddddddddeebbd..9
            .........ffffcbbbbbbb...
            ........fffffcbbbcccc...
            ........ffffcccbcccc....
            .......fffffcccb........
            ......fffffccccbb.......
            .....ffffffccccbb.......
            .....fffffcccccbb.......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb.9.
            .....fffffffffffcc......
            ...fffffffeeddeede..9...
            .....eeeddddddddde....19
            .....eeddddfdddfdee9..99
            ....eeedddfdddfddee..e..
            ....eeedddfdddfddee.e...
            ....eeeeddddddddeebbd..9
            .........ffffcbbbbbbb...
            ........fffffcbbbcccc...
            ........ffffcccbcccc....
            .......fffffcccb........
            ......fffffccccbb.......
            .....ffffffccccbb.......
            .....fffffcccccbb.......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb...
            .....fffffffffffcc.....9
            ...fffffffeeddeede...9..
            .....eeeddddddddde....19
            .....eeddddfdddfdee.9.99
            ....eeedddfdddfddee..e..
            ....eeedddfdddfddee.e..9
            ....eeeeddddddddeebbd...
            .........ffffcbbbbbbb...
            ........fffffcbbbcccc...
            ........ffffcccbcccc....
            .......fffffcccb........
            ......fffffccccbb.......
            .....ffffffccccbb.......
            .....fffffcccccbb.......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb...
            .....fffffffffffcc.....9
            ...fffffffeeddeede...9..
            .....eeeddddddddde....19
            .....eeddddfdddfdee.9.99
            ....eeedddfdddfddee..e..
            ....eeedddfdddfddee.e..9
            ....eeeeddddddddeebbd...
            .........ffffcbbbbbbb...
            ........fffffcbbbcccc...
            ........ffffcccbcccc....
            .......fffffcccb........
            ......fffffccccbb.......
            .....ffffffccccbb.......
            .....fffffcccccbb.......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb.9.
            .....fffffffffffcc......
            ...fffffffeeddeede..9...
            .....eeeddddddddde....19
            .....eeddddfdddfdee9..99
            ....eeedddfdddfddee..e..
            ....eeedddfdddfddee.e...
            ....eeeeddddddddeebbd..9
            .........ffffcbbbbbbb...
            ........fffffcbbbcccc...
            ........ffffcccbcccc....
            .......fffffcccb........
            ......fffffccccbb.......
            .....ffffffccccbb.......
            .....fffffcccccbb.......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb.9.
            .....fffffffffffcc......
            ...fffffffeeddeede..9...
            .....eeeddddddddde....19
            .....eeddddfdddfdee9..99
            ....eeedddfdddfddee..e..
            ....eeedddfdddfddee.e...
            ....eeeeddddddddeebbd..9
            .........ffffcbbbbbbb...
            ........fffffcbbbcccc...
            ........ffffcccbcccc....
            .......fffffcccb........
            ......fffffccccbb.......
            .....ffffffccccbb.......
            .....fffffcccccbb.......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `,img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb...
            .....fffffffffffcc......
            ...fffffffeeddeede......
            .....eeeddddddddde......
            .....eeddddfdddfdee.....
            ....eeedddfdddfddee.....
            ....eeedddfdddfddee.....
            ....eeeeddddddddeee.....
            .........ffffcb.........
            ........fffffcbb........
            ........ffffcccb........
            .......fffffcccb........
            ......fffffccccbb.......
            .....ffffffccccbb.......
            .....fffffcccccbbb......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `],
        100,
        false
        )
    }
})
controller.down.onEvent(ControllerButtonEvent.Released, function () {
    animation.setAction(Freya, ActionKind.standD)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.setAction(Freya, ActionKind.walkL)
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    animation.setAction(Freya, ActionKind.standR)
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    animation.setAction(Freya, ActionKind.standL)
})
function create_freya () {
    Freya = sprites.create(img`
        ........................
        ......fffccb............
        ....ffffffcccb..........
        .......fffffcccb........
        ......ffffffffccb.......
        ......fffffffffccbbbb...
        .....fffffffffffcc......
        ...fffffffeeddeede......
        .....eeeddddddddde......
        .....eeddddfdddfdee.....
        ....eeedddfdddfddee.....
        ....eeedddfdddfddee.....
        ....eeeeddddddddeee.....
        .........ffffcb.........
        ........fffffcbb........
        ........ffffcccb........
        .......fffffcccb........
        ......fffffccccbb.......
        .....ffffffccccbb.......
        .....fffffcccccbbb......
        ........eed.eed.........
        ........ffc.ffc.........
        ........................
        ........................
        `, SpriteKind.Player)
    controller.moveSprite(Freya)
    create_standing_animation()
    create_walking_animation()
}
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.setAction(Freya, ActionKind.WalkR)
})
controller.up.onEvent(ControllerButtonEvent.Released, function () {
    animation.setAction(Freya, ActionKind.standU)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.setAction(Freya, ActionKind.walkD)
})
function create_standing_animation () {
    animation_standing_right = animation.createAnimation(ActionKind.standR, 100)
    animation_standing_right.addAnimationFrame(img`
        ........................
        ......fffccb............
        ....ffffffcccb..........
        .......fffffcccb........
        ......ffffffffccb.......
        ......fffffffffccbbbb...
        .....fffffffffffcc......
        ...fffffffeeddeede......
        .....eeeddddddddde......
        .....eeddddfdddfdee.....
        ....eeedddfdddfddee.....
        ....eeedddfdddfddee.....
        ....eeeeddddddddeee.....
        .........ffffcb.........
        ........fffffcbb........
        ........ffffcccb........
        .......fffffcccb........
        ......fffffccccbb.......
        .....ffffffccccbb.......
        .....fffffcccccbbb......
        .........eeded..........
        .........ffcfc..........
        ........................
        ........................
        `)
    animation_standing_right.addAnimationFrame(img`
        ........................
        ......fffccb............
        ....ffffffcccb..........
        .......fffffcccb........
        ......ffffffffccb.......
        ......fffffffffccbbbb...
        .....fffffffffffcc......
        ...fffffffeeddeede......
        .....eeeddddddddde......
        .....eeddddddddddee.....
        ....eeeddddfdddfdee.....
        ....eeedddfdddfddee.....
        ....eeeeddddddddeee.....
        .........ffffcb.........
        ........fffffcbb........
        ........ffffcccb........
        .......fffffcccb........
        ......fffffccccbb.......
        .....ffffffccccbb.......
        .....fffffcccccbbb......
        .........eeded..........
        .........ffcfc..........
        ........................
        ........................
        `)
    for (let index = 0; index < 10; index++) {
        animation_standing_right.addAnimationFrame(img`
            ........................
            ......fffccb............
            ....ffffffcccb..........
            .......fffffcccb........
            ......ffffffffccb.......
            ......fffffffffccbbbb...
            .....fffffffffffcc......
            ...fffffffeeddeede......
            .....eeeddddddddde......
            .....eeddddfdddfdee.....
            ....eeedddfdddfddee.....
            ....eeedddfdddfddee.....
            ....eeeeddddddddeee.....
            .........ffffcb.........
            ........fffffcbb........
            ........ffffcccb........
            .......fffffcccb........
            ......fffffccccbb.......
            .....ffffffccccbb.......
            .....fffffcccccbbb......
            .........eeded..........
            .........ffcfc..........
            ........................
            ........................
            `)
    }
    animation_standing_left = animation.createAnimation(ActionKind.standL, 100)
    animation_standing_left.addAnimationFrame(img`
        ........................
        ............bccfff......
        ..........bcccffffff....
        ........bcccfffff.......
        .......bccffffffff......
        ...bbbbccfffffffff......
        ......ccfffffffffff.....
        ......edeeddeefffffff...
        ......edddddddddeee.....
        .....eedfdddfddddee.....
        .....eeddfdddfdddeee....
        .....eeddfdddfdddeee....
        .....eeeddddddddeeee....
        .........bcffff.........
        ........bbcfffff........
        ........bcccffff........
        ........bcccfffff.......
        .......bbccccfffff......
        .......bbccccffffff.....
        ......bbbcccccfffff.....
        ..........dedee.........
        ..........cfcff.........
        ........................
        ........................
        `)
    animation_standing_left.addAnimationFrame(img`
        ........................
        ............bccfff......
        ..........bcccffffff....
        ........bcccfffff.......
        .......bccffffffff......
        ...bbbbccfffffffff......
        ......ccfffffffffff.....
        ......edeeddeefffffff...
        ......edddddddddeee.....
        .....eeddddddddddee.....
        .....eedfdddfddddeee....
        .....eeddfdddfdddeee....
        .....eeeddddddddeeee....
        .........bcffff.........
        ........bbcfffff........
        ........bcccffff........
        ........bcccfffff.......
        .......bbccccfffff......
        .......bbccccffffff.....
        ......bbbcccccfffff.....
        ..........dedee.........
        ..........cfcff.........
        ........................
        ........................
        `)
    for (let index = 0; index < 10; index++) {
        animation_standing_left.addAnimationFrame(img`
            ........................
            ............bccfff......
            ..........bcccffffff....
            ........bcccfffff.......
            .......bccffffffff......
            ...bbbbccfffffffff......
            ......ccfffffffffff.....
            ......edeeddeefffffff...
            ......edddddddddeee.....
            .....eedfdddfddddee.....
            .....eeddfdddfdddeee....
            .....eeddfdddfdddeee....
            .....eeeddddddddeeee....
            .........bcffff.........
            ........bbcfffff........
            ........bcccffff........
            ........bcccfffff.......
            .......bbccccfffff......
            .......bbccccffffff.....
            ......bbbcccccfffff.....
            ..........dedee.........
            ..........cfcff.........
            ........................
            ........................
            `)
    }
    animation_standing_down = animation.createAnimation(ActionKind.standD, 100)
    animation_standing_down.addAnimationFrame(img`
        ........................
        ..........ffcc..........
        .........ffcbfccc.......
        ........fffccbfc........
        ......ffffcccbb.........
        ......ffffcccccbb.......
        ......fffcccccccc.......
        ..fffffffccccccccbbbb...
        ....fffffcccccccbbb.....
        .....eeedddddddeee......
        ....eeedfdddfdddeee.....
        ....eeeddfdddfddeee.....
        ....eeeddfdddfddeee.....
        ....eeedddddddddeee.....
        ......e.fffccbb.e.......
        ........ffccccb.........
        .......fffccccb.........
        .......ffcccccbb........
        ......fffcccccbb........
        ......fffcccccbbb.......
        ........eed.eed.........
        ........ffc.ffc.........
        ........................
        ........................
        `)
    animation_standing_down.addAnimationFrame(img`
        ........................
        ..........ffcc..........
        .........ffcbfccc.......
        ........fffccbfc........
        ......ffffcccbb.........
        ......ffffcccccbb.......
        ......fffcccccccc.......
        ..fffffffccccccccbbbb...
        ....fffffcccccccbbb.....
        .....eeedddddddeee......
        ....eeedddddddddeee.....
        ....eeedfdddfdddeee.....
        ....eeeddfdddfddeee.....
        ....eeedddddddddeee.....
        ......e.fffccbb.e.......
        ........ffccccb.........
        .......fffccccb.........
        .......ffcccccbb........
        ......fffcccccbb........
        ......fffcccccbbb.......
        ........eed.eed.........
        ........ffc.ffc.........
        ........................
        ........................
        `)
    for (let index = 0; index < 10; index++) {
        animation_standing_down.addAnimationFrame(img`
            ........................
            ..........ffcc..........
            .........ffcbfccc.......
            ........fffccbfc........
            ......ffffcccbb.........
            ......ffffcccccbb.......
            ......fffcccccccc.......
            ..fffffffccccccccbbbb...
            ....fffffcccccccbbb.....
            .....eeedddddddeee......
            ....eeedfdddfdddeee.....
            ....eeeddfdddfddeee.....
            ....eeeddfdddfddeee.....
            ....eeedddddddddeee.....
            ......e.fffccbb.e.......
            ........ffccccb.........
            .......fffccccb.........
            .......ffcccccbb........
            ......fffcccccbb........
            ......fffcccccbbb.......
            ........eed.eed.........
            ........ffc.ffc.........
            ........................
            ........................
            `)
    }
    animation_standing_up = animation.createAnimation(ActionKind.standU, 100)
    animation_standing_up.addAnimationFrame(img`
        ........................
        ..........fcb...........
        .........fffcb..........
        ........ffffcb..........
        ......fffffffbc.........
        ......fffffcfbcbb.......
        ......ffffccffbcb.......
        ......fffccccfbcb.......
        .ffffffffccccfbcbbbbb...
        ...fffffccccccccbb......
        ....effccccccccceee.....
        ....eeeccccccccdeee.....
        ....eeedddddddddeee.....
        ......eddddddddde.......
        ........fffccbb.........
        ........ffccccb.........
        .......fffccccb.........
        .......ffcccccbb........
        ......fffcccccbb........
        ......fffcccccbbb.......
        ........eed.eed.........
        ........ffc.ffc.........
        ........................
        ........................
        `)
    animation.attachAnimation(Freya, animation_standing_right)
    animation.attachAnimation(Freya, animation_standing_left)
    animation.attachAnimation(Freya, animation_standing_down)
}
function create_map () {
    scene.setBackgroundColor(0)
    if (room == 0) {
        scene.setTileMap(img`
            88888888877716e7778888888
            8888888887751fe7578888888
            8888888887771fe7778888888
            8888888877471f37478888888
            888877777772f377477888888
            888777557471e774747788888
            88877477774bfda7777778888
            887447777777bcfa477477788
            887774777747741e777747778
            887477747774771e577747778
            87477777757772fe774775778
            87475477777771f3777477778
            84774777747571e7747777778
            8477744777772ffa577774478
            877777777777b9f3777577778
            8777775777777b37747777578
            8777777774777777477777778
            8777477777777777774747778
            8874774774774757777774778
            8877775777777774777577478
            8877747777477777777777778
            8877774777775777577777788
            8887777477777747474475888
            8888777777757777777778888
            8888888888888888888888888
            `)
        scene.setTile(8, img`
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 c c c c 6 7 7 7 7 7 
            7 7 7 7 c c 6 7 7 5 5 6 6 7 7 7 
            7 7 c c 6 6 6 6 7 5 5 7 c c 7 7 
            7 c 6 6 6 7 7 7 7 7 7 5 6 c c 7 
            7 c 6 6 7 7 7 5 7 6 7 7 7 6 c c 
            c 6 6 7 7 6 7 7 7 6 7 7 6 6 6 c 
            c c 6 6 6 7 6 7 6 6 6 6 5 7 6 c 
            c c c c 6 7 7 6 7 7 7 6 7 6 6 c 
            7 c c 6 6 6 6 c 6 6 6 6 6 c c c 
            7 c c 6 6 c 6 6 c 6 c 6 6 c c 7 
            7 7 c c f f 6 6 c f f c c f 7 7 
            7 7 7 7 c f c c c f c f f 7 7 7 
            7 7 7 7 7 4 f f f c 7 e 7 7 7 7 
            7 7 7 7 7 7 e e e 7 7 4 7 7 7 7 
            7 7 7 7 7 7 7 e e 7 e 7 7 7 7 7 
            `, true)
        scene.setTile(5, img`
            5 7 5 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 1 7 7 
            7 7 7 1 1 7 7 7 7 7 7 7 1 7 1 7 
            7 7 3 1 1 3 7 7 7 5 7 7 6 1 6 7 
            7 1 1 6 6 1 1 7 7 5 7 7 7 7 7 7 
            7 d 1 7 7 1 d 7 7 6 7 7 7 7 7 7 
            7 6 3 1 1 3 6 7 7 7 7 5 7 7 7 7 
            7 7 6 d d 6 7 7 7 7 5 5 6 7 7 7 
            7 7 7 7 7 7 7 1 7 7 5 6 7 7 7 7 
            7 7 7 7 7 7 1 7 1 7 7 7 1 1 7 7 
            7 7 1 7 7 7 6 1 6 7 7 3 1 1 3 7 
            7 1 7 1 7 7 7 7 7 7 1 1 6 6 1 1 
            7 6 1 6 7 7 7 7 7 7 d 1 7 7 1 d 
            7 7 7 7 7 7 7 7 7 7 6 3 1 1 3 6 
            7 7 7 7 7 7 7 7 7 7 7 6 d d 6 7 
            7 7 5 7 7 7 7 7 7 7 7 7 7 7 7 7 
            `, false)
        scene.setTile(4, img`
            7 7 7 7 5 7 7 7 7 7 7 7 7 7 7 7 
            7 7 5 7 5 5 7 7 7 7 7 7 7 7 7 7 
            7 6 5 5 7 5 7 5 5 7 7 7 7 7 7 7 
            7 7 6 5 7 7 5 5 6 7 7 7 7 7 7 7 
            7 7 7 6 7 7 5 6 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 5 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 5 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 6 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 5 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 5 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 6 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 5 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            `, false)
        scene.setTile(11, img`
            7 6 d d d d d d d d d d d d d d 
            7 d d d d d d d d d d d d d d d 
            7 6 6 d d d d d d d 1 1 d d d d 
            7 7 6 d d d 1 d d d 1 1 d d d d 
            7 6 d d d d d d d d d d d d d d 
            7 6 d d d d d d d d d d d d d d 
            7 7 6 d d d d d d d d d d d d b 
            7 7 7 6 d d d d d d d d d d d d 
            7 6 d d d d d d d d d b d d d d 
            7 6 d d b b d d d d d d d d d d 
            7 7 6 d b b d d d d d d d 1 1 d 
            7 6 d d d d d d d d d d d 1 1 d 
            7 6 d d d d d d d d d d d d d d 
            7 7 6 d 6 d d 6 6 6 d d 6 6 d d 
            7 7 7 6 7 6 d 6 7 7 7 6 6 7 6 d 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            `, false)
        scene.setTile(3, img`
            d d d d d d d d d d d d d d 6 7 
            b d d d d d d d d d d d d d 6 7 
            d d d d d 1 d d d d d d d 6 7 7 
            d d d d d d d d d d d d d d 6 7 
            d d d d d d d d d b b d d d d 7 
            d d d d d d d d d b b d d d 6 7 
            d d d d d d d d d d d d d 6 7 7 
            d 1 1 d d d d d d d d d d d 6 7 
            d 1 1 d d d d 1 d d d d d d 6 7 
            d d d d d d d d d d d d d d 7 7 
            d d d d d d d d d d d d d 6 7 7 
            d d b d d d d d d d d 1 d 6 6 7 
            d d d d d d d d d d d d d 7 6 7 
            6 7 d 6 d 6 d d 6 6 6 d 6 7 7 7 
            7 6 7 7 6 7 6 6 6 7 7 6 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            `, false)
        scene.setTile(15, img`
            d d d d d d d d d d d d d d d d 
            d d d 1 1 d d d d d d d d b d d 
            d d d 1 1 d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d b d d d d d d b b d d d d d 
            d d d d d d d d d b b d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d b d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d b d d d 
            d d d d d d 1 d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d b d 
            `, false)
        scene.setTile(9, img`
            d d d d d d d d d d d d d d d d 
            d d d 1 1 d d d d d d d d b d d 
            d d d 1 1 d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d b d d d d d d b b d d d d d 
            d d d d d d d d d b b d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d b d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d b d d d 
            d d d d d d 1 d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d b d 
            `, false)
        scene.setTile(1, img`
            7 7 6 d d d 1 1 d d d d d d d d 
            7 6 6 d d d 1 1 d d d d d d d d 
            7 7 7 6 d d d d d d 1 d d d d d 
            7 6 6 d d d d d d d d d d d d d 
            7 7 6 6 d d d d d d d d d d d d 
            7 7 6 d d d d b d d d d d d d d 
            7 7 d d d d d d d d d d d d d 1 
            7 6 d d d d d d d d d d d d d d 
            7 6 d d d d d d d d d d b b d d 
            7 7 6 d d d d d d d d d b b d d 
            7 6 d d d d d d d 1 d d d d d d 
            7 d d b d d d d 1 1 1 d d d d d 
            7 6 d d d d d d d 1 d d d d d d 
            7 7 6 d d d d d d d d d d d d d 
            7 6 6 6 d d d d b d d d d d d d 
            7 7 d d d d d d d d d d d d d 1 
            `, false)
        scene.setTile(2, img`
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 6 7 7 6 6 6 7 6 7 7 6 7 
            7 7 7 6 d 6 6 6 d d 6 d 6 d 7 6 
            7 6 7 d d d d d d d d d d d d d 
            7 6 6 d d d d d d d d d d b d d 
            7 7 6 d d d d d d d d d d d d d 
            7 7 d d d d d d d d d d d d d d 
            7 6 d d d d b b d d d d d d d d 
            7 6 d d d d b b d d d 1 d d d d 
            7 7 6 d d d d d d d d d d d d d 
            7 6 d d d d d d d d d d d d 1 d 
            7 d d d d d d d d d 1 1 d d d d 
            7 6 d d d d d d d d 1 1 d d d d 
            7 7 6 d d d d d d d d d d d d d 
            7 6 d d b d d d d d d d d d d b 
            7 6 d d d d d d d d d d d d d d 
            `, false)
        scene.setTile(14, img`
            d d d d d d d d d d d d d d 6 7 
            d d d d d d d d d d d d d d 6 7 
            d d 1 d d d d d d d d d d 6 7 7 
            d 1 1 1 d d d d b d d d d d 6 7 
            d d 1 d d d d d d d d d d d d 7 
            d d d d d d d d d d d d d d 6 7 
            d d d d d d d d d d d 1 d 6 7 7 
            d d d d d d d d d d d d d 6 6 7 
            1 d d d d d d d d d d d d d 6 7 
            d d d d b b d d d d d d 6 7 7 7 
            d d d d b b d d d d d d d 6 6 7 
            d d d d d d d d d d d d d d 7 7 
            d d d d d d d d d d b d d d d 7 
            d d d d d d d d d d d d d 6 6 7 
            d d 1 d d d d d d d d d d 6 7 7 
            d d d d d d d d d d d d d d 6 7 
            `, false)
        scene.setTile(10, img`
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            d 6 7 6 6 7 7 7 6 d 6 7 6 7 7 7 
            d d 6 6 d d 6 6 6 d d 6 d 6 7 7 
            d d d d d d d d d d d d d d 6 7 
            d d d d b d d d d d 1 1 d d 6 7 
            d d d d d d d d d d 1 1 d 6 7 7 
            1 d d d d d d d 1 d d d d d 6 7 
            d d d d d d d d d d d d d d 6 7 
            d d d d d d d d d b d d 6 7 7 7 
            d d d b b d d d d d d d d 6 7 7 
            d d d b b d d d d d d d d d 6 7 
            d d d d d d d d d d d d d d 6 7 
            d d d d d d d d d d 1 d d 6 7 7 
            d d d d d d d d d d d d d 6 6 7 
            d d d d d b d d d d d d d d d 7 
            d d d d d d d d d d d d d d 6 7 
            `, false)
        scene.setTile(12, img`
            d 1 d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d b d d d d d 1 1 d d 
            d d d d d d d d d d d d 1 1 d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d 1 d d d b b d d d d d d d d d 
            d d d d d b b d d d d d d d b d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d b d d d d d d d 1 d d d d 
            d d d d d d d d d d d d d d d d 
            d 6 d d d d d d d 6 d d d d d d 
            6 7 6 d 6 7 d d d 7 6 7 7 6 d d 
            7 7 6 7 7 6 d 6 6 7 6 7 6 7 6 6 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            `, false)
        scene.setTile(13, img`
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            6 6 7 6 7 6 7 6 6 d 6 7 7 6 7 7 
            d d 6 7 7 6 7 d d d 7 6 d 6 7 6 
            d d d d d d 6 d d d d d d d 6 d 
            d d d d d d d d d d d d d d d d 
            d 1 1 d 1 d d d d d 1 d d d d d 
            d 1 1 d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d b d d d d d d d 1 d 
            d d d d d d d d d d d d d d d d 
            d d b d d d d d d d d b b d d d 
            d d d d d d d d d d d b b d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d 1 d d d d d d d d 
            d d d d d d d d d d d d d d 1 d 
            `, false)
        scene.setTile(6, img`
            d d d d d d d d d d d d d d d d 
            d d d 1 1 d d d d d d d d b d d 
            d d d 1 1 d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d b d d d d d d b b d d d d d 
            d d d d d d d d d b b d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d b d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d b d d d 
            d d d d d d 1 d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d b d 
            `, true)
    }
    if (room == 1) {
        scene.setTileMap(img`
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            7777777777777777777777777
            `)
        scene.setTile(8, img`
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 c c c c 6 7 7 7 7 7 
            7 7 7 7 c c 6 7 7 5 5 6 6 7 7 7 
            7 7 c c 6 6 6 6 7 5 5 7 c c 7 7 
            7 c 6 6 6 7 7 7 7 7 7 5 6 c c 7 
            7 c 6 6 7 7 7 5 7 6 7 7 7 6 c c 
            c 6 6 7 7 6 7 7 7 6 7 7 6 6 6 c 
            c c 6 6 6 7 6 7 6 6 6 6 5 7 6 c 
            c c c c 6 7 7 6 7 7 7 6 7 6 6 c 
            7 c c 6 6 6 6 c 6 6 6 6 6 c c c 
            7 c c 6 6 c 6 6 c 6 c 6 6 c c 7 
            7 7 c c f f 6 6 c f f c c f 7 7 
            7 7 7 7 c f c c c f c f f 7 7 7 
            7 7 7 7 7 4 f f f c 7 e 7 7 7 7 
            7 7 7 7 7 7 e e e 7 7 4 7 7 7 7 
            7 7 7 7 7 7 7 e e 7 e 7 7 7 7 7 
            `, true)
        scene.setTile(5, img`
            5 7 5 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 1 7 7 
            7 7 7 1 1 7 7 7 7 7 7 7 1 7 1 7 
            7 7 3 1 1 3 7 7 7 5 7 7 6 1 6 7 
            7 1 1 6 6 1 1 7 7 5 7 7 7 7 7 7 
            7 d 1 7 7 1 d 7 7 6 7 7 7 7 7 7 
            7 6 3 1 1 3 6 7 7 7 7 5 7 7 7 7 
            7 7 6 d d 6 7 7 7 7 5 5 6 7 7 7 
            7 7 7 7 7 7 7 1 7 7 5 6 7 7 7 7 
            7 7 7 7 7 7 1 7 1 7 7 7 1 1 7 7 
            7 7 1 7 7 7 6 1 6 7 7 3 1 1 3 7 
            7 1 7 1 7 7 7 7 7 7 1 1 6 6 1 1 
            7 6 1 6 7 7 7 7 7 7 d 1 7 7 1 d 
            7 7 7 7 7 7 7 7 7 7 6 3 1 1 3 6 
            7 7 7 7 7 7 7 7 7 7 7 6 d d 6 7 
            7 7 5 7 7 7 7 7 7 7 7 7 7 7 7 7 
            `, false)
        scene.setTile(4, img`
            7 7 7 7 5 7 7 7 7 7 7 7 7 7 7 7 
            7 7 5 7 5 5 7 7 7 7 7 7 7 7 7 7 
            7 6 5 5 7 5 7 5 5 7 7 7 7 7 7 7 
            7 7 6 5 7 7 5 5 6 7 7 7 7 7 7 7 
            7 7 7 6 7 7 5 6 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 5 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 5 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 6 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 5 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 5 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 6 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 5 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            `, false)
        scene.setTile(11, img`
            7 6 d d d d d d d d d d d d d d 
            7 d d d d d d d d d d d d d d d 
            7 6 6 d d d d d d d 1 1 d d d d 
            7 7 6 d d d 1 d d d 1 1 d d d d 
            7 6 d d d d d d d d d d d d d d 
            7 6 d d d d d d d d d d d d d d 
            7 7 6 d d d d d d d d d d d d b 
            7 7 7 6 d d d d d d d d d d d d 
            7 6 d d d d d d d d d b d d d d 
            7 6 d d b b d d d d d d d d d d 
            7 7 6 d b b d d d d d d d 1 1 d 
            7 6 d d d d d d d d d d d 1 1 d 
            7 6 d d d d d d d d d d d d d d 
            7 7 6 d 6 d d 6 6 6 d d 6 6 d d 
            7 7 7 6 7 6 d 6 7 7 7 6 6 7 6 d 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            `, false)
        scene.setTile(3, img`
            d d d d d d d d d d d d d d 6 7 
            b d d d d d d d d d d d d d 6 7 
            d d d d d 1 d d d d d d d 6 7 7 
            d d d d d d d d d d d d d d 6 7 
            d d d d d d d d d b b d d d d 7 
            d d d d d d d d d b b d d d 6 7 
            d d d d d d d d d d d d d 6 7 7 
            d 1 1 d d d d d d d d d d d 6 7 
            d 1 1 d d d d 1 d d d d d d 6 7 
            d d d d d d d d d d d d d d 7 7 
            d d d d d d d d d d d d d 6 7 7 
            d d b d d d d d d d d 1 d 6 6 7 
            d d d d d d d d d d d d d 7 6 7 
            6 7 d 6 d 6 d d 6 6 6 d 6 7 7 7 
            7 6 7 7 6 7 6 6 6 7 7 6 7 7 7 7 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            `, false)
        scene.setTile(15, img`
            d d d d d d d d d d d d d d d d 
            d d d 1 1 d d d d d d d d b d d 
            d d d 1 1 d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d b d d d d d d b b d d d d d 
            d d d d d d d d d b b d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d b d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d b d d d 
            d d d d d d 1 d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d b d 
            `, false)
        scene.setTile(9, img`
            d d d d d d d d d d d d d d d d 
            d d d 1 1 d d d d d d d d b d d 
            d d d 1 1 d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d b d d d d d d b b d d d d d 
            d d d d d d d d d b b d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d b d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d b d d d 
            d d d d d d 1 d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d b d 
            `, false)
        scene.setTile(1, img`
            7 7 6 d d d 1 1 d d d d d d d d 
            7 6 6 d d d 1 1 d d d d d d d d 
            7 7 7 6 d d d d d d 1 d d d d d 
            7 6 6 d d d d d d d d d d d d d 
            7 7 6 6 d d d d d d d d d d d d 
            7 7 6 d d d d b d d d d d d d d 
            7 7 d d d d d d d d d d d d d 1 
            7 6 d d d d d d d d d d d d d d 
            7 6 d d d d d d d d d d b b d d 
            7 7 6 d d d d d d d d d b b d d 
            7 6 d d d d d d d 1 d d d d d d 
            7 d d b d d d d 1 1 1 d d d d d 
            7 6 d d d d d d d 1 d d d d d d 
            7 7 6 d d d d d d d d d d d d d 
            7 6 6 6 d d d d b d d d d d d d 
            7 7 d d d d d d d d d d d d d 1 
            `, false)
        scene.setTile(2, img`
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            7 7 7 7 6 7 7 6 6 6 7 6 7 7 6 7 
            7 7 7 6 d 6 6 6 d d 6 d 6 d 7 6 
            7 6 7 d d d d d d d d d d d d d 
            7 6 6 d d d d d d d d d d b d d 
            7 7 6 d d d d d d d d d d d d d 
            7 7 d d d d d d d d d d d d d d 
            7 6 d d d d b b d d d d d d d d 
            7 6 d d d d b b d d d 1 d d d d 
            7 7 6 d d d d d d d d d d d d d 
            7 6 d d d d d d d d d d d d 1 d 
            7 d d d d d d d d d 1 1 d d d d 
            7 6 d d d d d d d d 1 1 d d d d 
            7 7 6 d d d d d d d d d d d d d 
            7 6 d d b d d d d d d d d d d b 
            7 6 d d d d d d d d d d d d d d 
            `, false)
        scene.setTile(14, img`
            d d d d d d d d d d d d d d 6 7 
            d d d d d d d d d d d d d d 6 7 
            d d 1 d d d d d d d d d d 6 7 7 
            d 1 1 1 d d d d b d d d d d 6 7 
            d d 1 d d d d d d d d d d d d 7 
            d d d d d d d d d d d d d d 6 7 
            d d d d d d d d d d d 1 d 6 7 7 
            d d d d d d d d d d d d d 6 6 7 
            1 d d d d d d d d d d d d d 6 7 
            d d d d b b d d d d d d 6 7 7 7 
            d d d d b b d d d d d d d 6 6 7 
            d d d d d d d d d d d d d d 7 7 
            d d d d d d d d d d b d d d d 7 
            d d d d d d d d d d d d d 6 6 7 
            d d 1 d d d d d d d d d d 6 7 7 
            d d d d d d d d d d d d d d 6 7 
            `, false)
        scene.setTile(10, img`
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            d 6 7 6 6 7 7 7 6 d 6 7 6 7 7 7 
            d d 6 6 d d 6 6 6 d d 6 d 6 7 7 
            d d d d d d d d d d d d d d 6 7 
            d d d d b d d d d d 1 1 d d 6 7 
            d d d d d d d d d d 1 1 d 6 7 7 
            1 d d d d d d d 1 d d d d d 6 7 
            d d d d d d d d d d d d d d 6 7 
            d d d d d d d d d b d d 6 7 7 7 
            d d d b b d d d d d d d d 6 7 7 
            d d d b b d d d d d d d d d 6 7 
            d d d d d d d d d d d d d d 6 7 
            d d d d d d d d d d 1 d d 6 7 7 
            d d d d d d d d d d d d d 6 6 7 
            d d d d d b d d d d d d d d d 7 
            d d d d d d d d d d d d d d 6 7 
            `, false)
        scene.setTile(12, img`
            d 1 d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d b d d d d d 1 1 d d 
            d d d d d d d d d d d d 1 1 d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d 1 d d d b b d d d d d d d d d 
            d d d d d b b d d d d d d d b d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d b d d d d d d d 1 d d d d 
            d d d d d d d d d d d d d d d d 
            d 6 d d d d d d d 6 d d d d d d 
            6 7 6 d 6 7 d d d 7 6 7 7 6 d d 
            7 7 6 7 7 6 d 6 6 7 6 7 6 7 6 6 
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            `, false)
        scene.setTile(13, img`
            7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
            6 6 7 6 7 6 7 6 6 d 6 7 7 6 7 7 
            d d 6 7 7 6 7 d d d 7 6 d 6 7 6 
            d d d d d d 6 d d d d d d d 6 d 
            d d d d d d d d d d d d d d d d 
            d 1 1 d 1 d d d d d 1 d d d d d 
            d 1 1 d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d b d d d d d d d 1 d 
            d d d d d d d d d d d d d d d d 
            d d b d d d d d d d d b b d d d 
            d d d d d d d d d d d b b d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d 1 d d d d d d d d 
            d d d d d d d d d d d d d d 1 d 
            `, false)
        scene.setTile(6, img`
            d d d d d d d d d d d d d d d d 
            d d d 1 1 d d d d d d d d b d d 
            d d d 1 1 d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d b d d d d d d b b d d d d d 
            d d d d d d d d d b b d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d b d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d d d d d 
            1 1 d d d d d d d d d d b d d d 
            d d d d d d 1 d d d d d d d d d 
            d d d d d d d d d d d d d d d d 
            d d d d d d d d d d d d d d b d 
            `, false)
    }
}
scene.onHitTile(SpriteKind.Player, 6, function (sprite) {
    room += 1
    create_map()
})
let animation_standing_up: animation.Animation = null
let animation_standing_down: animation.Animation = null
let animation_standing_left: animation.Animation = null
let animation_standing_right: animation.Animation = null
let animation_walking_up: animation.Animation = null
let animation_walking_down: animation.Animation = null
let animation_walking_right: animation.Animation = null
let animation_walking_left: animation.Animation = null
let Freya: Sprite = null
let room = 0
room = 0
create_freya()
create_map()
scene.cameraFollowSprite(Freya)
scene.placeOnRandomTile(Freya, 9)
